###
GET https://StreamlabsProxy.paulbecerra1.repl.co/api/streamlabs/jar/614e0c26b50434c9983e98d0

###
GET https://StreamlabsProxy.paulbecerra1.repl.co/api/streamlabs/unmute/614e187d52493aaed67bce36

###
GET https://streamlabs.com/api/v1.0/user?access_token=E10iN3fgXhHqfcp4TJUlUqzv9JR4bUT7DCoCkCdt

